spring.application.name=quiz-application

server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quiz_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:tiger}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}

# Jackson Configuration
spring.jackson.serialization.fail-on-empty-beans=false

# File Upload limit (just in case)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
